### PR TITLE
Show list of servers on home page.

### PR DESCRIPTION
**Pull request by skyqrose**
This should help people who land on the website know that there are public servers, which gives people another reason to download the launcher and play.

Also adds some hard-coded data about the servers (location and links), which is part of https://github.com/Ipmake/kocitylauncher/issues/23 . Maybe that info could eventually be in the API instead of hardcoded here, but this is easier for now.

I added TypeScript so I could have some checks that I'm handling the data correctly.

There's a CORS problem, though. The client directly calls https://api.kocity.xyz/stats/servers , and locally, the browser blocked the request because localhost wasn't an approved origin. So I did all my testing with static local data, not hitting the real API server. I think it might just work if it allows requests from https://kocity.xyz/ , but I can't test that. If not, then this would require a change to the API to allow requests from this origin.

Screenshot from 2023-06-10 17-13-45

And here's what it looks like in dark mode / if anything goes wrong with the request:

Screenshot from 2023-06-10 17-15-34

### CODE REVIEW

**Review by Ipmake — CHANGES_REQUESTED** [review]
Not a typescript user yet cause i haven't really looked into that. So i wont be able to maintain the documentation myself yet so i don't really like u just changing it to that. Keep it js for now please.

**Comment by Ipmake** [comment]
Great work with the server list tho. Looks awesome. Just the issue with typescript :(

**Comment by skyqrose** [comment]
oh hold on, there's a bug in that version, don't merge it yet

**Comment by skyqrose** [comment]
k, fixed.
I left a couple typedoc comments in where i think there useful for documentation

**Review by Ipmake — APPROVED** [review]

**Pull request merged**
